export const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILED = 'GET_TASKS_FAILED';
export const ADD_TASKS_REQUEST = 'ADD_TASKS_REQUEST';
export const ADD_TASKS_SUCCESS = 'ADD_TASKS_SUCCESS';